#!/bin/sh

# asound.conf.hdmi0 etc anlegen

#set -x

for (( i=0 ; i<3 ; i++ ))
do
    r=$(grep eld_valid /proc/asound/NVidia/eld#0.$i)
    v=$(echo $r | cut -d \  -f 2)
    if [ "$v" == "1" ]
    then
	ok=$i
    fi
done
if [ "$ok" == "" ]
then
    echo "Alsa not OK"
    echo "Alsa not OK" | mail -s "vdr3 Alsa not OK" jsffm@jsffm.lan
else
    echo "Alsa OK $ok"
    #cat /proc/asound/NVidia/eld#0.$ok
    if [ $ok -ne 1 ]
    then
	cat /proc/asound/NVidia/eld#0.$ok | mail -s "vdr3 Alsa $ok" jsffm@jsffm.lan
    fi
    #set -x
    cd /etc
    rm asound.conf
    ln -s asound.conf.hdmi$ok asound.conf
fi
